### ISSUE TITLE
Incorporating QBA and e-value calculations routinely into study definition in future

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/ics-research#109]
In the ICS paper we used Quantitative Bias Analysis. We did this  to calculate the minimum strengths of association between an unmeasured confounder and exposure or outcome, conditional on measured covariates, necessary to fully explain observed associations. 

You can see the files [in this folder](https://drive.google.com/drive/u/2/folders/1w5QIsHOQ2gmTcNao-ipY4wNYLrT2A56d). They are a mix of stata do files and calculations that can be done with excel like formulas
<details>
  <summary>Click to expand formula example</summary>
`=CONCATENATE(TEXT($I$4/(($A6*G$3)/($A6+G$3-1)), "0.00"), " (",TEXT($J$4/(($A6*G$3)/($A6+G$3-1)), "0.00"), ",", TEXT($K$4/(($A6*G$3)/($A6+G$3-1)), "0.00"), ")")`
</details>

We think we would like to use this in every study involving medicines in OpenSAFELY at this point. 

Jeremy did most of the work on this and himself and @annaschultze  may addmore. It would be good to see if there are parts of it that could at some point be automated or incorporated more formally into the routine study definition template.

**Comment by annaschultze** [comment]
Note: only e-values generated by e-value plots are used in this paper and analyses. These have been incorporated in the current workflow with the 'improve-worfklow' PR as of today. Closing this for completion.
